auth-server:
  # Public dummy UAA for local development usage only!
  # Username/password: credhub/password
  trust_store: src/test/resources/auth_server_trust_store.jks
  trust_store_password: changeit

encryption:
  key_creation_enabled: true
  providers:
  - provider_name: internal
    provider_type: internal
    keys:
    - encryption_password: opensesame
      provider_type: internal
      active: true
    - encryption_password: correcthorsebatterystaple
      provider_type: internal

security:
  oauth2:
    resource:
      id: credhub
  authorization:
    acls:
      enabled: true
    permissions:
    - path: /*
      actors:
      - "uaa-client:credhub_client"
      - "uaa-user:66e087aa-b6e2-4e98-b699-a0c17f175b27"
      operations: [read,write,delete,read_acl,write_acl]

logging:
  config: applications/credhub-api/src/main/resources/log4j2.properties

server:
  port: 9000
  ssl:
    enabled: true
    key_store: applications/credhub-api/src/test/resources/key_store.jks
    key_store_password: changeit
    key_password: changeit
    key_alias: cert
    ciphers: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    client_auth: want
    trust_store: applications/credhub-api/src/test/resources/trust_store.jks
    trust_store_password: changeit
    trust_store_type: JKS
    enabled-protocols: TLSv1.2

spring:
  profiles:
    include: dev-remote-uaa
  jpa:
    hibernate:
      ddl-auto: validate

certificates:
  concatenate_cas: false

management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: true
